"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { ArrowLeft, ArrowRight, BookOpen, Check, ChevronRight, GraduationCap, Languages, LoaderCircle, LockKeyhole, MapPin, ShieldCheck, Sparkles, Target, UserRound } from "lucide-react";
import { saveOnboarding } from "@/app/actions/learner";
import "./onboarding.css";

type Lang = "en" | "hi";
type Form = { fullName: string; institute: string; education: string; trade: string; semester: string; targetRole: string; location: string; mobility: string; language: Lang; consentProfile: boolean; consentAI: boolean; confirmUpdate: boolean };
const initial: Form = { fullName: "", institute: "", education: "ITI", trade: "Electrician", semester: "4", targetRole: "Industrial Electrician", location: "", mobility: "nearby", language: "en", consentProfile: true, consentAI: true, confirmUpdate: false };

const copy = {
  en: { kicker: "LET’S BUILD YOUR SKILL GRAPH", title: "A clearer path starts with your goal.", sub: "Four short steps help KarmaSetu personalize your diagnostic, learning and opportunities.", back: "Back", next: "Continue", finish: "Build my path", steps: ["About you", "Education", "Career goal", "Your control"] },
  hi: { kicker: "आइए आपका SKILL GRAPH बनाएँ", title: "साफ़ रास्ता आपके goal से शुरू होता है।", sub: "चार छोटे steps से KarmaSetu आपके diagnostic, learning और opportunities को personalize करता है।", back: "पीछे", next: "आगे बढ़ें", finish: "अपना path बनाएँ", steps: ["आपके बारे में", "Education", "Career goal", "आपका control"] },
};

const roles = ["Industrial Electrician", "Electrical Maintenance Technician", "Solar PV Installer", "CNC Machine Operator", "Quality Inspector", "Production Technician"];

export default function Onboarding() {
  const [lang, setLang] = useState<Lang>("en"), [step, setStep] = useState(0), [form, setForm] = useState<Form>(initial), [busy, setBusy] = useState(false), [message, setMessage] = useState(""), [existing, setExisting] = useState(false), [loadingProfile, setLoadingProfile] = useState(true); const router = useRouter(); const c = copy[lang];
  useEffect(() => { void (async () => { try { const response = await fetch("/api/account", { cache: "no-store" }); const body = await response.json(); if (!response.ok) throw new Error(body.error); const p = body.profile; const accountLang = (p?.preferred_language ?? body.account?.preferredLanguage ?? "en") as Lang; setLang(accountLang); setExisting(Boolean(p?.onboarding_completed_at)); setForm(v => ({...v,fullName:p?.full_name ?? body.account?.displayName ?? "",institute:p?.institute_name ?? "",education:p?.education_level ?? v.education,trade:p?.trade ?? v.trade,semester:String(p?.current_semester ?? v.semester),targetRole:p?.target_role_slug ? String(p.target_role_slug).split("-").map((x:string)=>x[0]?.toUpperCase()+x.slice(1)).join(" ") : v.targetRole,location:p?.home_location ?? "",mobility:p?.mobility_preference ?? v.mobility,language:accountLang,consentProfile:body.consents?.profile_personalization ?? v.consentProfile,consentAI:body.consents?.ai_personalization ?? v.consentAI})); } catch { setMessage("Your saved profile could not be loaded. Refresh before making changes."); } finally { setLoadingProfile(false); } })(); }, []);
  const update = <K extends keyof Form>(key: K, value: Form[K]) => setForm(v => ({ ...v, [key]: value }));
  const valid = step === 0 ? form.fullName.trim().length > 1 : step === 1 ? !!form.education && !!form.trade : step === 2 ? !!form.targetRole && !!form.location : form.consentProfile && (!existing || form.confirmUpdate);
  const finish = async () => { setBusy(true); setMessage(""); try { await saveOnboarding({...form,language:lang},crypto.randomUUID()); router.push("/diagnostic"); } catch(error) { setMessage(error instanceof Error?error.message:"Unable to save your profile"); setBusy(false); } };
  return <main className="onboard-shell"><aside className="onboard-story"><Link href="/" className="onboard-brand"><span>क</span><div>KarmaSetu <b>AI</b><small>कौशल से करियर तक</small></div></Link><div className="story-copy"><p><Sparkles /> {c.kicker}</p><h1>{c.title}</h1><span>{c.sub}</span></div><div className="story-proof"><ShieldCheck /><p><b>Your data stays yours.</b><span>Change visibility and AI consent any time.</span></p></div><div className="story-orbits"><i /><i /><i /><div><Target /></div></div></aside>
    <section className="onboard-main"><header><button className="onboard-lang" onClick={() => setLang(lang === "en" ? "hi" : "en")}><Languages /> {lang === "en" ? "हिंदी + EN" : "EN + हिंदी"}</button><span>Step {step + 1} of 4</span></header><div className="progress-line"><span style={{ width: `${(step + 1) * 25}%` }} /></div><div className="onboard-content"><ol className="stepper">{c.steps.map((s, i) => <li key={s} className={i === step ? "current" : i < step ? "done" : ""}><span>{i < step ? <Check /> : i + 1}</span><b>{s}</b></li>)}</ol>
      <div className="step-panel">{step === 0 && <><div className="step-heading"><UserRound /><div><p>STEP 01</p><h2>{lang === "en" ? "First, what should we call you?" : "सबसे पहले, हम आपको किस नाम से बुलाएँ?"}</h2><span>{lang === "en" ? "Only the information needed to personalize your experience." : "सिर्फ़ वही information जो आपके experience को personalize करने के लिए ज़रूरी है।"}</span></div></div>{loadingProfile?<div className="context-note"><LoaderCircle className="spin"/>Loading your saved profile…</div>:existing?<div className="context-note"><ShieldCheck/>Existing information is prefilled. Nothing changes until you explicitly confirm on the final step.</div>:null}<label>Full name<input autoFocus value={form.fullName} onChange={e => update("fullName", e.target.value)} placeholder="Your full name" /></label><label>Institute <small>Optional</small><input value={form.institute} onChange={e => update("institute", e.target.value)} placeholder="Your institute name" /></label></>}
      {step === 1 && <><div className="step-heading"><GraduationCap /><div><p>STEP 02</p><h2>{lang === "en" ? "Where are you learning today?" : "आप अभी कहाँ और क्या सीख रहे हैं?"}</h2><span>{lang === "en" ? "This sets a fair diagnostic level—never a permanent label." : "इससे diagnostic का सही level तय होगा—यह कोई permanent label नहीं है।"}</span></div></div><div className="field-grid"><label>Education level<select value={form.education} onChange={e => update("education", e.target.value)}><option>ITI</option><option>Diploma / Polytechnic</option><option>Bachelor&apos;s degree</option><option>Apprenticeship</option><option>Working professional</option></select></label><label>Current semester / year<select value={form.semester} onChange={e => update("semester", e.target.value)}>{[1,2,3,4,5,6,7,8].map(n => <option key={n}>{n}</option>)}</select></label></div><label>Trade or branch<input value={form.trade} onChange={e => update("trade", e.target.value)} placeholder="Electrician" /></label><div className="context-note"><BookOpen /> Your first diagnostic will adapt to this education level.</div></>}
      {step === 2 && <><div className="step-heading"><Target /><div><p>STEP 03</p><h2>{lang === "en" ? "What opportunity are you moving toward?" : "आप किस opportunity की ओर बढ़ना चाहते हैं?"}</h2><span>{lang === "en" ? "You can change the target role later. Your Skill Graph belongs to you." : "Target role बाद में बदला जा सकता है। आपका Skill Graph आपका है।"}</span></div></div><label>Target role<select value={form.targetRole} onChange={e => update("targetRole", e.target.value)}>{roles.map(r => <option key={r}>{r}</option>)}</select></label><label>Home city / district<div className="input-icon"><MapPin /><input value={form.location} onChange={e => update("location", e.target.value)} placeholder="Dehradun, Uttarakhand" /></div></label><fieldset><legend>Work-location preference</legend>{[["nearby","Near home"],["state","Anywhere in my state"],["relocate","Open to relocation"]].map(x => <button type="button" key={x[0]} className={form.mobility === x[0] ? "selected" : ""} onClick={() => update("mobility", x[0])}>{form.mobility === x[0] && <Check />}{x[1]}</button>)}</fieldset></>}
      {step === 3 && <><div className="step-heading"><LockKeyhole /><div><p>STEP 04</p><h2>{lang === "en" ? "You decide how your data helps you." : "आप तय करें कि आपका data आपकी कैसे मदद करे।"}</h2><span>{lang === "en" ? "Essential account processing is covered separately in the privacy notice." : "ज़रूरी account processing को privacy notice में अलग समझाया गया है।"}</span></div></div><div className="consent-card"><button type="button" onClick={() => update("consentProfile", !form.consentProfile)} className={form.consentProfile ? "checked" : ""}><span>{form.consentProfile && <Check />}</span><p><b>Personalize my Skill Graph</b><small>Use my assessments, learning and evidence to show readiness and next actions.</small></p></button><button type="button" onClick={() => update("consentAI", !form.consentAI)} className={form.consentAI ? "checked" : ""}><span>{form.consentAI && <Check />}</span><p><b>Use AI for personal guidance</b><small>Allow approved profile context in the AI coach. Sensitive identifiers are excluded.</small></p></button>{existing?<button type="button" onClick={()=>update("confirmUpdate",!form.confirmUpdate)} className={form.confirmUpdate?"checked":""}><span>{form.confirmUpdate&&<Check/>}</span><p><b>Confirm profile update</b><small>I reviewed the prefilled information and want to replace my existing profile values.</small></p></button>:null}</div><div className="control-note"><ShieldCheck /><p><b>Not used for automatic rejection.</b><span>AI recommends and explains. People make hiring decisions. You can withdraw optional consent later.</span></p></div></>}
      {message && <div className="onboard-message">{message}</div>}<footer><button className="back" disabled={step === 0} onClick={() => setStep(s => s - 1)}><ArrowLeft /> {c.back}</button>{step < 3 ? <button className="forward" disabled={!valid} onClick={() => setStep(s => s + 1)}>{c.next}<ArrowRight /></button> : <button className="forward" disabled={!valid || busy} onClick={finish}>{busy ? <LoaderCircle className="spin" /> : c.finish}<ChevronRight /></button>}</footer></div></div></section>
  </main>;
}
