"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import { ArrowRight, BrainCircuit, Check, CheckCircle2, ChevronRight, Clock3, Languages, Lightbulb, LoaderCircle, MessageSquareText, RefreshCw, ShieldCheck, Sparkles, Target, Trophy, Volume2 } from "lucide-react";
import { completeInterview } from "@/app/actions/learner";
import "./interview.css";

type Lang="en"|"hi"; type Response={answer:string;feedback:string};
const questions=[
 {en:"Walk me through how you would safely isolate an industrial control panel before beginning work.",hi:"Industrial control panel पर काम शुरू करने से पहले आप उसे safely isolate कैसे करेंगे?",focus:"Safety reasoning",prompt:"Evaluate this entry-level interview answer for safety completeness, clarity, and correctness. Give two strengths and one specific improvement. Never make a hiring decision."},
 {en:"A three-phase motor hums but does not start. How would you diagnose the problem step by step?",hi:"Three-phase motor hum करता है लेकिन start नहीं होता। आप step by step diagnosis कैसे करेंगे?",focus:"Problem solving",prompt:"Evaluate this troubleshooting answer for safe sequence, technical relevance, and explanation. Give concise evidence-based feedback, not a hiring decision."},
 {en:"Tell me about the wiring-board project you completed. What did you test, and what would you improve next time?",hi:"अपने wiring-board project के बारे में बताएँ। आपने क्या test किया और अगली बार क्या improve करेंगे?",focus:"Evidence explanation",prompt:"Evaluate whether this answer uses concrete project evidence, testing detail, reflection, and clear communication. Give actionable coaching only."},
];

export default function Interview(){const[lang,setLang]=useState<Lang>("en"),[stage,setStage]=useState<"intro"|"room"|"result">("intro"),[index,setIndex]=useState(0),[answer,setAnswer]=useState(""),[responses,setResponses]=useState<Response[]>([]),[feedback,setFeedback]=useState(""),[busy,setBusy]=useState(false);const q=questions[index];const scores=useMemo(()=>{const words=responses.map(r=>r.answer.trim().split(/\s+/).length);const avg=words.length?words.reduce((a,b)=>a+b,0)/words.length:0;return{technical:Math.min(88,58+Math.round(avg/4)),clarity:Math.min(86,55+Math.round(avg/5)),evidence:Math.min(90,50+responses.filter(r=>/test|check|verify|measure|isolate|project/i.test(r.answer)).length*10),confidence:74}},[responses]);
 const submitAnswer=async()=>{if(answer.trim().length<20)return;setBusy(true);let coaching="Good start. Add the exact safety check or measurement you would use, then explain why it comes before the next step.";try{const res=await fetch("/api/ai",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({task:"interviewer",messages:[{role:"user",content:`${q.prompt}\n\nCandidate answer (${lang}): ${answer}`}]})});const data=await res.json();coaching=data.message||data.error||coaching}catch{}setFeedback(coaching);setBusy(false)};
 const next=async()=>{const nextResponses=[...responses,{answer,feedback}];setResponses(nextResponses);setAnswer("");setFeedback("");if(index<questions.length-1){setIndex(i=>i+1);return}await completeInterview({targetRoleSlug:"industrial-electrician",language:lang,responses:nextResponses.map((r,i)=>({position:i+1,questionText:lang==="en"?questions[i].en:questions[i].hi,answerText:r.answer,aiFeedback:r.feedback})),scoreSummary:scores},crypto.randomUUID());setStage("result")};
 const c=lang==="en"?{title:"Practice the interview before it counts.",sub:"Three focused questions for an entry-level Industrial Electrician role. Get evidence-based coaching after every response.",start:"Start mock interview",private:"Practice stays private",question:"INTERVIEW QUESTION",respond:"Your response",placeholder:"Explain your thinking step by step. Use a real example when you can…",feedback:"Karma’s coaching",next:"Next question",finish:"See my feedback"}:{title:"Real interview से पहले practice करें।",sub:"Entry-level Industrial Electrician role के लिए तीन focused questions। हर response के बाद evidence-based coaching पाएँ।",start:"Mock interview शुरू करें",private:"Practice private रहती है",question:"INTERVIEW QUESTION",respond:"आपका response",placeholder:"अपनी thinking step by step बताएँ। जहाँ हो सके real example दें…",feedback:"Karma की coaching",next:"अगला question",finish:"अपना feedback देखें"};
 if(stage==="intro")return <main className="interview-intro"><header><Link href="/dashboard" className="interview-brand"><span>क</span><div>KarmaSetu <b>AI</b><small>कौशल से करियर तक</small></div></Link><button onClick={()=>setLang(lang==="en"?"hi":"en")}><Languages/>{lang==="en"?"हिंदी + EN":"EN + हिंदी"}</button></header><section><div className="intro-copy"><p><Sparkles/>AI MOCK INTERVIEW · PRACTICE MODE</p><h1>{c.title}</h1><span>{c.sub}</span><div className="intro-points"><div><Clock3/><p><b>10–12 minutes</b><small>Pause between questions</small></p></div><div><MessageSquareText/><p><b>Text-first practice</b><small>No camera or microphone required</small></p></div><div><ShieldCheck/><p><b>{c.private}</b><small>Not shared with employers</small></p></div></div><button onClick={()=>setStage("room")}>{c.start}<ArrowRight/></button><small>AI coaching supports preparation. It does not make hiring decisions.</small></div><div className="intro-visual"><div className="ai-interviewer"><BrainCircuit/><span>KARMA INTERVIEWER</span><i>READY</i></div><div className="speech-card"><Volume2/><p>“Tell me how you think—not just the final answer.”</p></div><div className="orbit o1"/><div className="orbit o2"/></div></section></main>;
 if(stage==="result")return <main className="interview-result"><section><div className="result-medal"><Trophy/></div><p>PRACTICE COMPLETE</p><h1>{lang==="en"?"You’re explaining your skills more clearly.":"आप अपनी skills को और clearly explain कर रहे हैं।"}</h1><span>{lang==="en"?"This readiness snapshot is coaching guidance, not an employer score.":"यह readiness snapshot coaching guidance है, employer score नहीं।"}</span><div className="interview-score"><div><b>{Math.round((scores.technical+scores.clarity+scores.evidence+scores.confidence)/4)}</b><small>practice readiness</small></div><aside>{Object.entries(scores).map(([k,v])=><div key={k}><span>{k}</span><i><em style={{width:`${v}%`}}/></i><b>{v}</b></div>)}</aside></div><div className="result-insights"><article><CheckCircle2/><p><b>Strongest signal</b><span>You used a safe sequence and explained why isolation comes first.</span></p></article><article><Lightbulb/><p><b>Next improvement</b><span>Add exact measurements and expected readings when describing troubleshooting.</span></p></article></div><div className="response-review"><h2>Your response review</h2>{responses.map((r,i)=><details key={i}><summary><span>{i+1}</span><p><b>{questions[i].focus}</b><small>{lang==="en"?questions[i].en:questions[i].hi}</small></p><ChevronRight/></summary><div><b>Your answer</b><p>{r.answer}</p><b>Coaching</b><p>{r.feedback}</p></div></details>)}</div><div className="result-actions"><Link href="/dashboard">Update my journey<ArrowRight/></Link><button onClick={()=>{setStage("intro");setIndex(0);setResponses([])}}><RefreshCw/>Practice again</button></div></section></main>;
 return <main className="interview-room"><header><Link href="/dashboard" className="interview-brand"><span>क</span><div>KarmaSetu <b>AI</b><small>कौशल से करियर तक</small></div></Link><div><span><ShieldCheck/>Private practice</span><button onClick={()=>setLang(lang==="en"?"hi":"en")}><Languages/>{lang==="en"?"हिंदी + EN":"EN + हिंदी"}</button></div></header><div className="room-progress"><span style={{width:`${(index+1)/questions.length*100}%`}}/></div><section><aside><p>MOCK INTERVIEW</p><h2>Industrial Electrician</h2><span>Entry level · Technical + behavioral</span><div className="interview-steps">{questions.map((x,i)=><div key={x.en} className={i===index?"active":i<index?"done":""}><i>{i<index?<Check/>:i+1}</i><p><b>{x.focus}</b><small>{i<index?"Coached":i===index?"In progress":"Upcoming"}</small></p></div>)}</div><div className="room-safe"><ShieldCheck/><p><b>Practice, not screening</b><span>Your response is used only for coaching unless you later choose to share it.</span></p></div></aside><article><div className="interviewer-row"><div><BrainCircuit/></div><p><span>KARMA · AI INTERVIEWER</span><b>{c.question} {index+1} OF {questions.length}</b></p><em>LISTENING</em></div><h1>{lang==="en"?q.en:q.hi}</h1><div className="focus-tag"><Target/>Focus: {q.focus}</div><label>{c.respond}<textarea value={answer} onChange={e=>{setAnswer(e.target.value.slice(0,1600));setFeedback("")}} placeholder={c.placeholder}/><small>{answer.trim()?answer.trim().split(/\s+/).length:0} words · {answer.length}/1600</small></label>{!feedback?<button className="get-coaching" disabled={answer.trim().length<20||busy} onClick={submitAnswer}>{busy?<LoaderCircle className="spin"/>:<BrainCircuit/>}{busy?"Reviewing your response…":"Get coaching"}</button>:<div className="coaching"><div><Sparkles/><p><b>{c.feedback}</b><span>Evidence-based practice feedback</span></p></div><p>{feedback}</p><div><button onClick={()=>setFeedback("")}><RefreshCw/>Improve this answer</button><button onClick={next}>{index<questions.length-1?c.next:c.finish}<ArrowRight/></button></div></div>}</article></section></main>}
