"use client";

import { useEffect, useRef, useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { ArrowRight, BrainCircuit, BriefcaseBusiness, Building2, CheckCircle2, ChevronDown, GraduationCap, Languages, LockKeyhole, Menu, Play, Sparkles, Target, Users, X, Zap } from "lucide-react";
import * as THREE from "three";
import { createClient } from "@supabase/supabase-js";

type Lang = "en" | "hi"; type Copy = { en: string; hi: string }; const tx = (c: Copy, l: Lang) => c[l];
const journey = [
  { n: "01", icon: Target, title: { en: "Discover", hi: "खुद को पहचानें" }, body: { en: "A diagnostic maps what you know against the skills real employers need.", hi: "AI diagnostic आपकी मौजूदा skills को industry की वास्तविक ज़रूरतों से map करता है।" } },
  { n: "02", icon: GraduationCap, title: { en: "Learn", hi: "सीखें" }, body: { en: "A personal pathway closes only the gaps that are holding you back.", hi: "Personal learning path केवल उन्हीं skill gaps को पूरा करता है जो आपको रोक रहे हैं।" } },
  { n: "03", icon: BrainCircuit, title: { en: "Prove", hi: "क्षमता साबित करें" }, body: { en: "Projects, verified credentials and AI interviews turn learning into evidence.", hi: "Projects, verified credentials और AI interviews learning को प्रमाण में बदलते हैं।" } },
  { n: "04", icon: BriefcaseBusiness, title: { en: "Get matched", hi: "सही अवसर पाएँ" }, body: { en: "Your JobReady Index connects you to roles where your skills can win.", hi: "JobReady Index आपको उन roles से जोड़ता है जहाँ आपकी skills सबसे उपयुक्त हैं।" } },
];
const roles = [
  { icon: GraduationCap, title: { en: "For learners", hi: "Students के लिए" }, body: { en: "Know where you stand. Build what matters. Walk into interviews ready.", hi: "जानें कि आप कहाँ खड़े हैं। सही skills बनाएँ और interview के लिए तैयार हों।" }, cta: { en: "Start my journey", hi: "अपनी journey शुरू करें" } },
  { icon: Building2, title: { en: "For institutes", hi: "Institutes के लिए" }, body: { en: "See skill gaps early, improve outcomes and make placement data actionable.", hi: "Skill gaps जल्दी पहचानें, outcomes सुधारें और placement data को actionable बनाएँ।" }, cta: { en: "Transform outcomes", hi: "Outcomes बेहतर बनाएँ" } },
  { icon: Users, title: { en: "For employers", hi: "Employers के लिए" }, body: { en: "Hire from verified evidence—not another pile of unfiltered résumés.", hi: "Unfiltered résumés की भीड़ नहीं—verified evidence से सही talent चुनें।" }, cta: { en: "Find verified talent", hi: "Verified talent खोजें" } },
];

function SkillGraph() {
  const mount = useRef<HTMLDivElement>(null);
  useEffect(() => { if (!mount.current) return; const host = mount.current, scene = new THREE.Scene(), camera = new THREE.PerspectiveCamera(45, host.clientWidth / host.clientHeight, .1, 100); camera.position.z = 6;
    const reduceMotion = matchMedia("(prefers-reduced-motion: reduce)").matches; const renderer = new THREE.WebGLRenderer({ antialias: true, alpha: true, powerPreference: "low-power" }); renderer.setPixelRatio(Math.min(devicePixelRatio, 1.4)); renderer.setSize(host.clientWidth, host.clientHeight); host.appendChild(renderer.domElement);
    const group = new THREE.Group(); scene.add(group); const nodes: THREE.Mesh[] = [], positions: THREE.Vector3[] = [];
    for (let i = 0; i < 34; i++) { const phi = Math.acos(-1 + 2 * i / 34), theta = Math.sqrt(34 * Math.PI) * phi, p = new THREE.Vector3(Math.cos(theta) * Math.sin(phi), Math.sin(theta) * Math.sin(phi), Math.cos(phi)).multiplyScalar(2); positions.push(p); const mesh = new THREE.Mesh(new THREE.IcosahedronGeometry(i % 7 === 0 ? .11 : .055, 0), new THREE.MeshBasicMaterial({ color: i % 7 === 0 ? 0xffc928 : 0x7ee7db })); mesh.position.copy(p); nodes.push(mesh); group.add(mesh); }
    const pts: THREE.Vector3[] = []; positions.forEach((p, i) => positions.slice(i + 1).forEach(q => { if (p.distanceTo(q) < 1.15) pts.push(p, q); })); group.add(new THREE.LineSegments(new THREE.BufferGeometry().setFromPoints(pts), new THREE.LineBasicMaterial({ color: 0x3acbbd, transparent: true, opacity: .22 })));
    group.add(new THREE.Mesh(new THREE.SphereGeometry(2.5, 40, 40), new THREE.MeshBasicMaterial({ color: 0x103c51, transparent: true, opacity: .14, wireframe: true })));
    let mx = 0, my = 0, frame = 0; const move = (e: PointerEvent) => { mx = (e.clientX / innerWidth - .5) * .35; my = (e.clientY / innerHeight - .5) * .25; }; addEventListener("pointermove", move);
    const animate = () => { if (!reduceMotion) frame = requestAnimationFrame(animate); group.rotation.y += reduceMotion ? 0 : .0028 + (mx - group.rotation.y * .02) * .002; group.rotation.x += reduceMotion ? 0 : (my - group.rotation.x) * .025; if(!reduceMotion)nodes.forEach((n, i) => n.scale.setScalar(1 + Math.sin(Date.now() * .002 + i) * .15)); renderer.render(scene, camera); }; animate();
    const resize = () => { camera.aspect = host.clientWidth / host.clientHeight; camera.updateProjectionMatrix(); renderer.setSize(host.clientWidth, host.clientHeight); }; addEventListener("resize", resize);
    return () => { cancelAnimationFrame(frame); removeEventListener("resize", resize); removeEventListener("pointermove", move); renderer.dispose(); if (renderer.domElement.parentNode === host) host.removeChild(renderer.domElement); };
  }, []); return <div ref={mount} className="skill-graph" aria-label="Animated 3D skill graph" />;
}

function AuthModal({ open, close, lang }: { open: boolean; close: () => void; lang: Lang }) {
  const [mode, setMode] = useState<"login" | "signup">("login"), [email, setEmail] = useState(""), [password, setPassword] = useState(""), [message, setMessage] = useState(""), [busy, setBusy] = useState(false);
  const submit = async (e: React.FormEvent) => { e.preventDefault(); setBusy(true); setMessage(""); const url = process.env.NEXT_PUBLIC_SUPABASE_URL, key = process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;
    if (!url || !key) { setMessage(lang === "en" ? "Demo is ready. Add Supabase keys to activate secure email access." : "Demo तैयार है। Secure email access के लिए Supabase keys जोड़ें।"); setBusy(false); return; }
    const supabase = createClient(url, key); const result = mode === "login" ? await supabase.auth.signInWithPassword({ email, password }) : await supabase.auth.signUp({ email, password, options: { emailRedirectTo: `${location.origin}/onboarding` } }); setMessage(result.error ? result.error.message : mode === "login" ? "Welcome back." : "Check your email to verify your account."); setBusy(false); if (!result.error && mode === "login") location.href = "/dashboard"; };
  return <AnimatePresence>{open && <motion.div className="modal-backdrop" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onMouseDown={e => e.target === e.currentTarget && close()}><motion.div className="auth-card" initial={{ opacity: 0, y: 24, scale: .97 }} animate={{ opacity: 1, y: 0, scale: 1 }} exit={{ opacity: 0, y: 18 }}><button className="modal-close" onClick={close} aria-label="Close"><X /></button><div className="brand-mark small">क</div><p className="eyebrow"><LockKeyhole size={14} /> {mode === "login" ? "SECURE ACCESS" : "CREATE YOUR PROFILE"}</p><h2>{mode === "login" ? tx({ en: "Your next step is waiting.", hi: "आपका अगला कदम तैयार है।" }, lang) : tx({ en: "Begin your KarmaSetu journey.", hi: "अपनी KarmaSetu journey शुरू करें।" }, lang)}</h2><p>{tx({ en: "One profile for assessment, learning, interviews and opportunities.", hi: "Assessment, learning, interviews और opportunities के लिए एक profile।" }, lang)}</p><form onSubmit={submit}><label>Email address<input type="email" required value={email} onChange={e => setEmail(e.target.value)} placeholder="you@example.com" /></label><label>Password<input type="password" minLength={6} required value={password} onChange={e => setPassword(e.target.value)} placeholder="Minimum 6 characters" /></label><button className="primary wide" disabled={busy}>{busy ? "Please wait…" : mode === "login" ? tx({ en: "Continue securely", hi: "सुरक्षित रूप से आगे बढ़ें" }, lang) : tx({ en: "Create my account", hi: "अपना account बनाएँ" }, lang)} <ArrowRight size={18} /></button></form>{message && <div className="form-message">{message}</div>}<button className="text-button" onClick={() => setMode(mode === "login" ? "signup" : "login")}>{mode === "login" ? tx({ en: "New here? Create an account", hi: "पहली बार आए हैं? Account बनाएँ" }, lang) : tx({ en: "Already registered? Sign in", hi: "पहले से registered हैं? Sign in करें" }, lang)}</button></motion.div></motion.div>}</AnimatePresence>;
}

export default function Home() {
  const [lang, setLang] = useState<Lang>("en"), [auth, setAuth] = useState(false), [menu, setMenu] = useState(false);
  return <main><nav><a className="brand" href="#top"><span className="brand-mark">क</span><span>KarmaSetu <b>AI</b><small>कौशल से करियर तक</small></span></a><div className={`nav-links ${menu ? "open" : ""}`}><a href="#journey">How it works</a><a href="#ecosystem">For everyone</a><a href="#intelligence">AI intelligence</a><button className="language" onClick={() => setLang(lang === "en" ? "hi" : "en")}><Languages size={17} /> {lang === "en" ? "हिंदी + EN" : "EN + हिंदी"}</button><button className="nav-cta" onClick={() => setAuth(true)}>Sign in <ArrowRight size={16} /></button></div><button className="menu" onClick={() => setMenu(!menu)} aria-label="Menu">{menu ? <X /> : <Menu />}</button></nav>
  <section className="hero" id="top"><div className="aurora a1" /><div className="aurora a2" /><div className="hero-copy"><div className="live-pill"><span /> India&apos;s employability intelligence network</div><h1>{tx({ en: "Talent is everywhere. Opportunity should find it.", hi: "Talent हर जगह है। Opportunity को उस तक पहुँचना चाहिए।" }, lang)}</h1><p>{tx({ en: "KarmaSetu turns potential into proof—connecting learners, institutes and industry through one living Skill Graph.", hi: "KarmaSetu potential को proof में बदलता है—learners, institutes और industry को एक live Skill Graph से जोड़ता है।" }, lang)}</p><div className="hero-actions"><button className="primary" onClick={() => setAuth(true)}>{tx({ en: "Build my Skill Graph", hi: "अपना Skill Graph बनाएँ" }, lang)} <ArrowRight size={19} /></button><a className="ghost" href="#story"><span><Play size={16} fill="currentColor" /></span>{tx({ en: "See the story", hi: "पूरी कहानी देखें" }, lang)}</a></div><div className="trust"><div><b>200+</b><span>Pilot learners</span></div><div><b>15</b><span>Target institutes</span></div><div><b>10</b><span>MSME partners</span></div></div></div><div className="hero-visual"><SkillGraph /><div className="orbit-label l1"><Sparkles size={14} /> Verified skills</div><div className="orbit-label l2"><Zap size={14} /> JobReady Index</div><div className="orbit-label l3"><BriefcaseBusiness size={14} /> Live opportunity</div></div><a href="#story" className="scroll-cue">SCROLL TO EXPLORE <ChevronDown /></a></section>
  <section className="problem" id="story"><p className="eyebrow">THE DISTANCE BETWEEN LEARNING AND LIVELIHOOD</p><div className="split-heading"><h2>{tx({ en: "India trains millions. Industry still can’t find them.", hi: "भारत लाखों students को train करता है। Industry फिर भी सही talent नहीं खोज पाती।" }, lang)}</h2><p>{tx({ en: "Degrees show where someone studied. They rarely show what someone can do today. That missing evidence costs students their confidence and employers their time.", hi: "Degree बताती है कि कोई कहाँ पढ़ा। यह कम ही बताती है कि वह आज क्या कर सकता है। इसी missing evidence से students का confidence और employers का समय—दोनों कम होते हैं।" }, lang)}</p></div><div className="stats"><article><b>50%+</b><span>technical graduates are often rated not job-ready</span></article><article><b>60–90</b><span>days can be spent filling entry-level industrial roles</span></article><article><b>1 bridge</b><span>from verified skill to a meaningful first salary</span></article></div></section>
  <section className="journey" id="journey"><div className="section-head"><p className="eyebrow">THE KARMASETU JOURNEY</p><h2>{tx({ en: "From “What can I do?” to “When can I start?”", hi: "“मैं क्या कर सकता हूँ?” से “मैं कब शुरू कर सकता हूँ?” तक।" }, lang)}</h2></div><div className="journey-grid">{journey.map((item, i) => <motion.article key={item.n} initial={{ opacity: 0, y: 35 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: i * .1 }}><div className="step-top"><span>{item.n}</span><item.icon /></div><h3>{tx(item.title, lang)}</h3><p>{tx(item.body, lang)}</p>{i < 3 && <ArrowRight className="step-arrow" />}</motion.article>)}</div></section>
  <section className="intelligence" id="intelligence"><div className="intel-visual"><div className="rings r1" /><div className="rings r2" /><div className="rings r3" /><div className="index-core"><small>JOBREADY</small><b>82</b><span>Strong match</span></div><div className="metric m1"><span>Technical</span><b>88</b></div><div className="metric m2"><span>Communication</span><b>74</b></div><div className="metric m3"><span>Practical</span><b>84</b></div></div><div className="intel-copy"><p className="eyebrow">THE INTELLIGENCE LAYER</p><h2>{tx({ en: "A score that moves as you grow.", hi: "एक score जो आपकी growth के साथ बदलता है।" }, lang)}</h2><p>{tx({ en: "The JobReady Index brings assessment, verified learning, projects, AI interview performance and employer feedback into one explainable readiness signal.", hi: "JobReady Index assessment, verified learning, projects, AI interview performance और employer feedback को एक explainable readiness signal में बदलता है।" }, lang)}</p><ul><li><CheckCircle2 /> Clear next-best action, not a black box</li><li><CheckCircle2 /> Evidence linked to every skill claim</li><li><CheckCircle2 /> Consent-led visibility for employers</li></ul><button className="secondary" onClick={() => setAuth(true)}>Preview my readiness <ArrowRight size={18} /></button></div></section>
  <section className="ecosystem" id="ecosystem"><div className="section-head center"><p className="eyebrow">ONE NETWORK · SHARED OUTCOMES</p><h2>{tx({ en: "When every side can see the same truth, everyone moves faster.", hi: "जब सभी एक ही सच देखते हैं, तो हर कोई तेज़ी से आगे बढ़ता है।" }, lang)}</h2></div><div className="role-grid">{roles.map((role, i) => <motion.article key={i} whileHover={{ y: -8 }}><div className="role-icon"><role.icon /></div><h3>{tx(role.title, lang)}</h3><p>{tx(role.body, lang)}</p><button onClick={() => setAuth(true)}>{tx(role.cta, lang)} <ArrowRight size={17} /></button></motion.article>)}</div></section>
  <section className="learning"><div className="learning-copy"><p className="eyebrow">LEARNING THAT LEADS SOMEWHERE</p><h2>{tx({ en: "Watch. Practice. Prove it.", hi: "देखें। Practice करें। अपनी क्षमता साबित करें।" }, lang)}</h2><p>{tx({ en: "Curated YouTube lessons explain concepts. Guided projects and Drive resources turn them into evidence. Progress returns to your Skill Graph—not a forgotten playlist.", hi: "Curated YouTube lessons concepts समझाते हैं। Guided projects और Drive resources उन्हें evidence में बदलते हैं। आपकी progress Skill Graph में जुड़ती है—किसी भूली हुई playlist में नहीं।" }, lang)}</p><div className="content-tags"><span>YouTube learning paths</span><span>Drive resource library</span><span>Project evidence</span></div></div><div className="video-shell"><div className="video-top"><span /><span /><span /></div><div className="video-stage"><button aria-label="Play sample lesson"><Play size={28} fill="currentColor" /></button><div><small>FOUNDATION · 08:42</small><b>Reading an engineering drawing</b><span>Lesson placeholder · Add your YouTube ID</span></div></div><div className="video-progress"><span /></div></div></section>
  <section className="cta-section"><div className="cta-glow" /><p className="eyebrow">YOUR POTENTIAL IS ALREADY THERE</p><h2>{tx({ en: "Let’s make it visible.", hi: "आइए, इसे दुनिया के सामने लाएँ।" }, lang)}</h2><p>{tx({ en: "One profile. A clear path. Real evidence. Better opportunities.", hi: "एक profile। साफ़ रास्ता। वास्तविक evidence। बेहतर opportunities।" }, lang)}</p><button className="primary light" onClick={() => setAuth(true)}>{tx({ en: "Begin my journey", hi: "अपनी journey शुरू करें" }, lang)} <ArrowRight /></button></section>
  <footer><div className="brand"><span className="brand-mark">क</span><span>KarmaSetu <b>AI</b><small>कौशल से करियर तक</small></span></div><p>Bridging India&apos;s industry readiness gap with explainable, evidence-led AI.</p><div><a href="#journey">How it works</a><a href="#ecosystem">Ecosystem</a><a href="/trust">Trust center</a><a href="mailto:hello@karmasetu.ai">Contact</a></div><small>© 2026 KarmaSetu AI · Responsible AI · Privacy by design</small></footer><AuthModal open={auth} close={() => setAuth(false)} lang={lang} /></main>;
}
