"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import "../../components/role-explorer.css";
type Role={slug:string;title_en:string;title_hi:string|null;sector:string;description_en:string;description_hi:string|null;tasks:unknown;skill_requirements:unknown;wage_min:number|null;wage_max:number|null;currency:string;updated_at:string};
const format=(v:unknown):string=>Array.isArray(v)?v.map(format).join(" · "):typeof v==="object"&&v?Object.values(v).map(format).join(" · "):String(v??"Not provided");
export default function Roles(){
  const [roles,setRoles]=useState<Role[]>([]),[saved,setSaved]=useState<string[]>([]),[compared,setCompared]=useState<Role[]>([]),[showCompare,setShowCompare]=useState(false),[lang,setLang]=useState(false),[q,setQ]=useState(""),[query,setQuery]=useState(""),[cursor,setCursor]=useState(""),[next,setNext]=useState<string|null>(null),[error,setError]=useState(""),[loading,setLoading]=useState(true),[busy,setBusy]=useState("");
  useEffect(()=>{const controller=new AbortController();const start=setTimeout(()=>{setLoading(true);setError("");void fetch(`/api/roles?${new URLSearchParams({q:query,cursor})}`,{signal:controller.signal}).then(async r=>{const body=await r.json();if(!r.ok)throw Error(body.error);return body;}).then(body=>{setRoles(body.items);setSaved(body.savedSlugs);setNext(body.nextCursor);}).catch(e=>{if(e.name!=="AbortError")setError(e.message);}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});},0);return()=>{clearTimeout(start);controller.abort();};},[query,cursor]);
  const save=async(role:Role)=>{setBusy(role.slug);setError("");try{const response=await fetch("/api/roles",{method:saved.includes(role.slug)?"DELETE":"POST",headers:{"content-type":"application/json"},body:JSON.stringify({slug:role.slug})});const body=await response.json();if(!response.ok)throw Error(response.status===401?"Sign in to save roles to your account.":body.error);setSaved(old=>body.saved?[...old,role.slug]:old.filter(s=>s!==role.slug));}catch(e){setError(e instanceof Error?e.message:"Unable to save");}finally{setBusy("");}};
  return <main className="role-explorer"><header><Link href="/">क KarmaSetu AI</Link><Link href="/dashboard">My dashboard</Link><button onClick={()=>setLang(v=>!v)}>{lang?"English":"हिंदी + EN"}</button></header><section><p>APPROVED CAREER REGISTRY</p><h1>{lang?"अपनी skills के लिए career खोजें।":"Explore approved career pathways."}</h1><p>Role descriptions and requirements come from the published registry. Personalized readiness is shown only in your authenticated skill profile.</p><form onSubmit={e=>{e.preventDefault();setQuery(q);setCursor("");}}><label>Search role title<input value={q} onChange={e=>setQ(e.target.value)} maxLength={100}/></label><button>Search</button><button type="button" disabled={compared.length<2} onClick={()=>setShowCompare(v=>!v)}>Compare selected ({compared.length}/3)</button></form>{error?<p role="alert">{error} <Link href="/auth">Sign in</Link></p>:null}
  {showCompare&&compared.length>=2?<div className="role-comparison"><h2>Role comparison</h2><table><thead><tr><th>Field</th>{compared.map(r=><th key={r.slug}>{r.title_en}</th>)}</tr></thead><tbody>{(["sector","tasks","skill_requirements"] as const).map(field=><tr key={field}><th>{field.replaceAll("_"," ")}</th>{compared.map(r=><td key={r.slug}>{format(r[field])}</td>)}</tr>)}</tbody></table></div>:null}
  {loading?<p role="status">Loading published pathways…</p>:roles.length===0?<p>No published roles match this search. New pathways appear after review and publication.</p>:<div className="role-results">{roles.map(role=><article key={role.slug}><p>{role.sector}</p><h2>{lang&&role.title_hi?role.title_hi:role.title_en}</h2><p>{lang&&role.description_hi?role.description_hi:role.description_en}</p><p><b>Skills: </b>{format(role.skill_requirements)}</p><p><b>Declared wage range: </b>{role.wage_min!==null&&role.wage_max!==null?`${role.currency} ${role.wage_min.toLocaleString()}–${role.wage_max.toLocaleString()}`:"Not published"}</p><details><summary>Tasks and evidence expectations</summary><p>{format(role.tasks)}</p></details><div><button disabled={Boolean(busy)} aria-pressed={saved.includes(role.slug)} onClick={()=>void save(role)}>{saved.includes(role.slug)?"Remove saved role":"Save role"}</button><label><input type="checkbox" checked={compared.some(r=>r.slug===role.slug)} disabled={compared.length>=3&&!compared.some(r=>r.slug===role.slug)} onChange={e=>setCompared(old=>e.target.checked?[...old,role]:old.filter(r=>r.slug!==role.slug))}/>Compare</label></div><small>Registry updated {new Date(role.updated_at).toLocaleDateString()}</small></article>)}</div>}
  <div className="role-pagination"><button onClick={()=>setCursor("")} disabled={!cursor||loading}>First page</button><button onClick={()=>setCursor(next!)} disabled={!next||loading}>Next page</button></div></section></main>;
}
