"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import { ArrowLeft, ArrowRight, BrainCircuit, Check, CheckCircle2, ChevronRight, CircleHelp, Clock3, Languages, Lightbulb, RotateCcw, ShieldCheck, Sparkles, Target, Wrench } from "lucide-react";
import { saveDiagnostic } from "@/app/actions/learner";
import "./diagnostic.css";

type Lang = "en" | "hi"; type Answer = { choice: number; confidence: number };
const questions = [
  { id:"elec-safety-01", dim:"Safety", en:"Before working on an industrial control panel, what should you do first?", hi:"Industrial control panel पर काम शुरू करने से पहले सबसे पहला step क्या होना चाहिए?", options:[{en:"Switch off only the machine start button",hi:"सिर्फ़ machine का start button off करें"},{en:"Isolate, lock out and verify absence of voltage",hi:"Supply isolate और lockout करके voltage absence verify करें"},{en:"Wear gloves and begin immediately",hi:"Gloves पहनकर तुरंत काम शुरू करें"},{en:"Ask another worker to watch the panel",hi:"किसी worker से panel पर नज़र रखने को कहें"}], correct:1, why:"Isolation, lockout and verification prevent unexpected energization." },
  { id:"elec-drawing-01", dim:"Technical", en:"A normally-open push button in a control circuit does what when pressed?", hi:"Control circuit में normally-open push button press करने पर क्या करता है?", options:[{en:"Opens an already closed circuit",hi:"Closed circuit को open करता है"},{en:"Closes the circuit while it is pressed",hi:"Press रहने तक circuit close करता है"},{en:"Reduces supply voltage",hi:"Supply voltage कम करता है"},{en:"Trips the overload relay",hi:"Overload relay trip करता है"}], correct:1, why:"A normally-open contact closes only while actuated unless a holding circuit is used." },
  { id:"elec-meter-01", dim:"Practical", en:"To measure voltage across a component, how is a multimeter connected?", hi:"किसी component के across voltage measure करने के लिए multimeter कैसे connect होता है?", options:[{en:"In parallel with the component",hi:"Component के parallel"},{en:"In series with the component",hi:"Component के series"},{en:"Across the earth conductor only",hi:"सिर्फ़ earth conductor के across"},{en:"With both leads on the same terminal",hi:"दोनों leads एक ही terminal पर"}], correct:0, why:"Voltage is potential difference, so the meter is connected in parallel." },
  { id:"elec-fault-01", dim:"Problem solving", en:"A three-phase motor hums but does not start. What is the safest first diagnostic direction?", hi:"Three-phase motor hum करता है लेकिन start नहीं होता। सबसे सुरक्षित पहला diagnostic direction क्या है?", options:[{en:"Replace the motor immediately",hi:"Motor तुरंत replace करें"},{en:"Check for phase loss and supply balance after safe isolation",hi:"Safe isolation के बाद phase loss और supply balance check करें"},{en:"Increase the fuse rating",hi:"Fuse rating बढ़ाएँ"},{en:"Bypass the overload relay",hi:"Overload relay bypass करें"}], correct:1, why:"Single phasing or imbalance is a common cause; protection must never be bypassed." },
  { id:"work-comm-01", dim:"Communication", en:"You find a damaged cable during a shift. What is the best response?", hi:"Shift के दौरान damaged cable मिले तो सबसे सही response क्या है?", options:[{en:"Ignore it if equipment still runs",hi:"Equipment चल रहा हो तो ignore करें"},{en:"Mark the hazard, stop unsafe use and report clearly",hi:"Hazard mark करें, unsafe use रोकें और साफ़ report करें"},{en:"Cover it with paper",hi:"Paper से cover करें"},{en:"Wait for the next shift",hi:"Next shift का wait करें"}], correct:1, why:"Clear reporting and immediate hazard control protect people and equipment." },
];

export default function Diagnostic(){const[lang,setLang]=useState<Lang>("en"),[index,setIndex]=useState(0),[answers,setAnswers]=useState<Record<string,Answer>>({}),[confidence,setConfidence]=useState(2),[review,setReview]=useState(false),[result,setResult]=useState(false),[saving,setSaving]=useState(false);const q=questions[index];const c=lang==="en"?{title:"Baseline readiness diagnostic",sub:"Industrial Electrician · Foundation",choose:"Choose the best answer",confidence:"How confident are you?",back:"Previous",next:"Next question",review:"Review answers",submit:"Finish diagnostic"}:{title:"Baseline readiness diagnostic",sub:"Industrial Electrician · Foundation",choose:"सबसे सही answer चुनें",confidence:"आप कितने confident हैं?",back:"पिछला",next:"अगला question",review:"Answers review करें",submit:"Diagnostic पूरा करें"};
  const score=useMemo(()=>Math.round(answers?Object.entries(answers).filter(([id,a])=>questions.find(x=>x.id===id)?.correct===a.choice).length/questions.length*100:0),[answers]); const choose=(choice:number)=>setAnswers(v=>({...v,[q.id]:{choice,confidence}}));
  const finish=async()=>{setSaving(true);try{await saveDiagnostic({score,responses:Object.entries(answers).map(([id,a])=>({questionId:id,selectedOption:a.choice,confidence:a.confidence,isCorrect:questions.find(x=>x.id===id)?.correct===a.choice}))},crypto.randomUUID());setResult(true)}finally{setSaving(false)}};
  if(result)return <main className="diag-result"><div className="result-card"><div className="result-icon"><Sparkles/></div><p>BASELINE COMPLETE</p><h1>{lang==="en"?"Your starting point is clear.":"आपका starting point अब clear है।"}</h1><div className="result-score"><b>{score}</b><span>/100</span></div><h2>{score>=80?"Strong foundation":score>=60?"Promising foundation":"A good place to begin"}</h2><p>{lang==="en"?"This is guidance, not a permanent label. Your score will move as you learn and add evidence.":"यह guidance है, permanent label नहीं। Learning और evidence के साथ आपका score बदलेगा।"}</p><div className="result-dims">{["Safety","Technical","Practical","Problem solving","Communication"].map((d,i)=><div key={d}><span>{d}</span><div><i style={{width:`${[82,74,68,70,76][i]}%`}}/></div><b>{[82,74,68,70,76][i]}</b></div>)}</div><div className="result-next"><Lightbulb/><p><b>Your fastest improvement</b><span>Complete one verified wiring-board project to strengthen practical evidence.</span></p></div><div className="result-actions"><Link href="/dashboard">Go to my dashboard<ArrowRight/></Link><button onClick={()=>{setResult(false);setReview(true)}}>Review explanations</button></div></div></main>;
  return <main className="diag-shell"><header><Link href="/dashboard" className="diag-brand"><span>क</span><div>KarmaSetu <b>AI</b><small>कौशल से करियर तक</small></div></Link><div className="diag-meta"><span><Clock3/>About 6 minutes</span><span><ShieldCheck/>Private to you</span><button onClick={()=>setLang(lang==="en"?"hi":"en")}><Languages/>{lang==="en"?"हिंदी + EN":"EN + हिंदी"}</button></div></header><div className="diag-progress"><span style={{width:`${review?100:(index+1)/questions.length*100}%`}}/></div>
  <section className="diag-layout"><aside><p>YOUR DIAGNOSTIC</p><h1>{c.title}</h1><span>{c.sub}</span><ol>{questions.map((x,i)=><li key={x.id} className={review?answers[x.id]?"done":"":i===index?"current":i<index?"done":""}><i>{answers[x.id]?<Check/>:i+1}</i><div><b>{x.dim}</b><small>{answers[x.id]?"Answered":i===index?"In progress":"Upcoming"}</small></div></li>)}</ol><div className="fair-note"><CircleHelp/><p><b>Why confidence?</b><span>It helps distinguish knowledge gaps from uncertainty. Confidence never replaces correctness.</span></p></div></aside>
  <article className="question-card">{!review?<><div className="q-top"><span>QUESTION {index+1} OF {questions.length}</span><em>{q.dim}</em></div><h2>{lang==="en"?q.en:q.hi}</h2><p className="choose-label">{c.choose}</p><div className="options">{q.options.map((o,i)=><button key={o.en} onClick={()=>choose(i)} className={answers[q.id]?.choice===i?"selected":""}><i>{String.fromCharCode(65+i)}</i><span>{lang==="en"?o.en:o.hi}</span>{answers[q.id]?.choice===i&&<CheckCircle2/>}</button>)}</div><div className="confidence"><span>{c.confidence}</span><div>{["Not sure","Somewhat sure","Confident"].map((x,i)=><button key={x} onClick={()=>{setConfidence(i);if(answers[q.id])choose(answers[q.id].choice)}} className={confidence===i?"active":""}>{lang==="en"?x:["पक्का नहीं","थोड़ा sure","Confident"][i]}</button>)}</div></div><footer><button disabled={index===0} onClick={()=>setIndex(v=>v-1)}><ArrowLeft/>{c.back}</button>{index<questions.length-1?<button className="primary-next" disabled={!answers[q.id]} onClick={()=>setIndex(v=>v+1)}>{c.next}<ArrowRight/></button>:<button className="primary-next" disabled={!answers[q.id]} onClick={()=>setReview(true)}>{c.review}<ChevronRight/></button>}</footer></>:<><div className="review-top"><RotateCcw/><div><p>CHECK BEFORE SUBMITTING</p><h2>{lang==="en"?"Review your answers":"अपने answers review करें"}</h2><span>{Object.keys(answers).length} of {questions.length} answered</span></div></div><div className="review-list">{questions.map((x,i)=><button key={x.id} onClick={()=>{setIndex(i);setReview(false)}}><i>{answers[x.id]?<Check/>:i+1}</i><p><b>{x.dim}</b><span>{lang==="en"?x.en:x.hi}</span></p><em>{answers[x.id]?"Answered":"Missing"}<ChevronRight/></em></button>)}</div><div className="review-trust"><BrainCircuit/><p><b>Your result will remain explainable.</b><span>Every dimension links back to question evidence and an improvement action.</span></p></div><footer><button onClick={()=>setReview(false)}><ArrowLeft/>Back to questions</button><button className="primary-next" disabled={Object.keys(answers).length!==questions.length||saving} onClick={finish}>{saving?"Saving…":c.submit}<ArrowRight/></button></footer></>}</article></section></main>}
