"use server";
import {z} from "zod";
import {requirePersona} from "@/lib/auth/dal";
import {createClient} from "@/lib/supabase/server";

const onboardingSchema=z.object({fullName:z.string().trim().min(2).max(120),institute:z.string().trim().max(160),education:z.string().trim().min(2).max(80),trade:z.string().trim().min(2).max(100),semester:z.coerce.number().int().min(1).max(12),targetRole:z.string().trim().min(2).max(120),location:z.string().trim().min(2).max(160),mobility:z.enum(["nearby","state","relocate"]),language:z.enum(["en","hi"]),consentProfile:z.boolean(),consentAI:z.boolean(),confirmUpdate:z.boolean().default(false)});
export async function saveOnboarding(input:unknown,idempotencyKey:string){const viewer=await requirePersona("learner","admin");if(viewer.demo)return{ok:true,demo:true};const parsed=onboardingSchema.parse(input),sb=await createClient();if(!sb)throw new Error("Persistence is unavailable");const{data:existing,error:readError}=await sb.from("learner_profiles").select("onboarding_completed_at").eq("user_id",viewer.id).maybeSingle();if(readError)throw new Error(readError.message);if(existing?.onboarding_completed_at&&!parsed.confirmUpdate)throw new Error("Confirm that you want to update your existing learner profile.");const{error}=await sb.rpc("complete_learner_onboarding",{p_idempotency_key:idempotencyKey,p_full_name:parsed.fullName,p_institute_name:parsed.institute,p_education_level:parsed.education,p_trade:parsed.trade,p_semester:parsed.semester,p_target_role_slug:parsed.targetRole.toLowerCase().replaceAll(" ","-"),p_home_location:parsed.location,p_mobility:parsed.mobility,p_language:parsed.language,p_profile_consent:parsed.consentProfile,p_ai_consent:parsed.consentAI});if(error)throw new Error(error.message);return{ok:true,demo:false}}

const diagnosticSchema=z.object({score:z.number().int().min(0).max(100),responses:z.array(z.object({questionId:z.string().min(1).max(100),selectedOption:z.number().int().min(0).max(10),confidence:z.number().int().min(0).max(2),isCorrect:z.boolean()})).min(1).max(100)});
export async function saveDiagnostic(input:unknown,idempotencyKey:string){const viewer=await requirePersona("learner","admin");if(viewer.demo)return{ok:true,demo:true};const parsed=diagnosticSchema.parse(input),sb=await createClient();if(!sb)throw new Error("Persistence is unavailable");const{error}=await sb.rpc("complete_diagnostic_attempt",{p_idempotency_key:idempotencyKey,p_assessment_slug:"industrial-electrician-baseline",p_assessment_version:"1.0",p_score:parsed.score,p_responses:parsed.responses});if(error)throw new Error(error.message);return{ok:true,demo:false}}

export async function submitApplication(jobId:string,idempotencyKey:string){const viewer=await requirePersona("learner","admin");if(viewer.demo)return{ok:true,demo:true};const validJob=z.string().min(2).max(120).parse(jobId),sb=await createClient();if(!sb)throw new Error("Persistence is unavailable");const{error}=await sb.rpc("submit_job_application",{p_idempotency_key:idempotencyKey,p_job_id:validJob});if(error)throw new Error(error.message);return{ok:true,demo:false}}

const lessonSchema=z.object({lessonId:z.string().min(1).max(120),progressPercent:z.number().int().min(0).max(100),lastPositionSeconds:z.number().int().min(0).max(86400)});
export async function completeLesson(input:unknown,idempotencyKey:string){const viewer=await requirePersona("learner","admin");if(viewer.demo)return{ok:true,demo:true};const parsed=lessonSchema.parse(input),sb=await createClient();if(!sb)throw new Error("Persistence is unavailable");const{error}=await sb.rpc("complete_learning_lesson",{p_idempotency_key:idempotencyKey,p_lesson_id:parsed.lessonId,p_progress_percent:parsed.progressPercent,p_last_position_seconds:parsed.lastPositionSeconds});if(error)throw new Error(error.message);return{ok:true,demo:false}}

const interviewSchema=z.object({targetRoleSlug:z.string().min(2).max(120),language:z.enum(["en","hi"]),responses:z.array(z.object({position:z.number().int().min(1).max(50),questionText:z.string().min(2).max(2000),answerText:z.string().min(2).max(5000),aiFeedback:z.string().max(8000)})).min(1).max(20),scoreSummary:z.record(z.string(),z.number().min(0).max(100))});
export async function completeInterview(input:unknown,idempotencyKey:string){const viewer=await requirePersona("learner","admin");if(viewer.demo)return{ok:true,demo:true};const parsed=interviewSchema.parse(input),sb=await createClient();if(!sb)throw new Error("Persistence is unavailable");const{error}=await sb.rpc("complete_interview_session",{p_idempotency_key:idempotencyKey,p_target_role_slug:parsed.targetRoleSlug,p_language:parsed.language,p_responses:parsed.responses,p_score_summary:parsed.scoreSummary});if(error)throw new Error(error.message);return{ok:true,demo:false}}

export async function saveEvidenceMetadata(input:unknown,idempotencyKey:string){const viewer=await requirePersona("learner","admin");if(viewer.demo)return{ok:true,demo:true};void input;void idempotencyKey;throw new Error("Evidence upload is paused until the pilot malware-scanning pipeline is approved.")}
