"use server";
import {z} from "zod";
import {requireOrganizationRole} from "@/lib/auth/dal";
import {createClient} from "@/lib/supabase/server";

const uuid=z.string().uuid();
export async function createCohort(input:unknown){const parsed=z.object({organizationId:uuid,name:z.string().trim().min(2).max(120),trade:z.string().trim().min(2).max(100),academicYear:z.string().regex(/^20\d{2}-\d{2}$/),semester:z.number().int().min(1).max(8)}).parse(input);const viewer=await requireOrganizationRole(parsed.organizationId,"institute",["owner","admin","placement_officer"]);if(viewer.demo)return{ok:true,demo:true};const sb=await createClient();const{data,error}=await sb!.from("cohorts").insert({organization_id:parsed.organizationId,name:parsed.name,trade:parsed.trade,academic_year:parsed.academicYear,semester:parsed.semester,status:"active"}).select("id").single();if(error)throw new Error(error.message);return{ok:true,id:data.id}}

export async function assignSupportAction(input:unknown){const parsed=z.object({organizationId:uuid,cohortId:uuid.nullable(),learnerUserId:uuid,signalType:z.string().min(2).max(80),suggestedAction:z.string().max(1000),assignedTo:uuid.nullable(),dueAt:z.string().datetime().nullable()}).parse(input);const viewer=await requireOrganizationRole(parsed.organizationId,"institute",["owner","admin","placement_officer","faculty"]);if(viewer.demo)return{ok:true,demo:true};const sb=await createClient();const{data,error}=await sb!.from("learner_support_actions").insert({organization_id:parsed.organizationId,cohort_id:parsed.cohortId,learner_user_id:parsed.learnerUserId,signal_type:parsed.signalType,suggested_action:parsed.suggestedAction,assigned_to:parsed.assignedTo,due_at:parsed.dueAt,status:parsed.assignedTo?"assigned":"open"}).select("id").single();if(error)throw new Error(error.message);return{ok:true,id:data.id}}

export async function moveApplicationStage(input:unknown){const parsed=z.object({organizationId:uuid,applicationId:uuid,stage:z.enum(["matched","consent","shortlist","interview","offer","hired","closed"]),note:z.string().trim().max(2000).optional()}).parse(input);const viewer=await requireOrganizationRole(parsed.organizationId,"employer",["owner","admin","recruiter"]);if(viewer.demo)return{ok:true,demo:true};const sb=await createClient();const{error}=await sb!.from("hiring_pipeline_entries").upsert({application_id:parsed.applicationId,stage:parsed.stage,owner_user_id:viewer.id,stage_updated_at:new Date().toISOString()},{onConflict:"application_id"});if(error)throw new Error(error.message);if(parsed.note){const{error:noteError}=await sb!.from("hiring_team_notes").insert({application_id:parsed.applicationId,author_user_id:viewer.id,body:parsed.note});if(noteError)throw new Error(noteError.message)}return{ok:true}}

export async function openGovernanceCase(input:unknown){const parsed=z.object({organizationId:uuid,caseType:z.enum(["grievance","appeal","fairness_review","security_incident","data_request"]),severity:z.enum(["low","medium","high","critical"]),summary:z.string().trim().min(10).max(4000),subjectRef:z.string().max(200).optional()}).parse(input);const viewer=await requireOrganizationRole(parsed.organizationId,"program",["program_admin","auditor","grievance_officer"]);if(viewer.demo)return{ok:true,demo:true};const sb=await createClient();const{data,error}=await sb!.from("governance_cases").insert({program_organization_id:parsed.organizationId,case_type:parsed.caseType,severity:parsed.severity,summary:parsed.summary,subject_ref:parsed.subjectRef,status:"open"}).select("id").single();if(error)throw new Error(error.message);return{ok:true,id:data.id}}
